server.port=8085
caching.ttl.wifi=600000
caching.ttl.cal=300000

spring.thymeleaf.cache=false
spring.resources.cache.period=0

# Contact Library Systems to get the .env file
# spring.config.import=optional:file:../brocklibutil.env[.properties]
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=${mysql_jdbc_url}
spring.datasource.username=${mysql_username}
spring.datasource.password=${mysql_password}